# Generated by Django 4.0.6 on 2022-09-06 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('amount', models.PositiveIntegerField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
