# Generated by Django 4.0.6 on 2022-09-10 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='prod',
        ),
        migrations.AddField(
            model_name='orders',
            name='Total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Orders_details',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orders')),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.products')),
            ],
        ),
    ]
