# Generated by Django 4.0.6 on 2022-10-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_orders_user_wishlist_privatewishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='PrivateWishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
