# Generated by Django 4.0.6 on 2022-10-08 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_remove_wishlist_user_delete_privatewishlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
